### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by ralyodio** [hoytech/strfry#88]
```
services:
  strfry-nostr-relay:
    build: .
    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - ./data/strfry-db:/app/strfry-db
    ports:
      - "7071:7777"
    networks:
      - follows_network
networks:
    follows_network:
      name: follows_network

```

what am i doing wrong? get connection refused when i try `curl http://localhost:7071`
